hackev:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  left_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_wheel_joint
  right_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: right_wheel_joint
  arm_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint
  tail_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: tail_joint

